# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68d1df12cbaaeb18a0480a5704c1e22cac03f8d2fe8f2224ad17f88249efc050604423651052c4453e25d30443fd5397aab4f4683d58ddf51dfe598c0006e6ec

test:
  secret_key_base: 92c2b4c25c63bc2d1bce4ebad81b50e2f2a0ae7dc8ed54d1fbc03b40d81faeb16d5f8a7f594fe08bea20bd0f46786db305486670507b7322eb242c965f61688d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
